ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'

mapping:
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'zonky2 <info@e-spin.de>'
